const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { DatabaseSync } = require('node:sqlite');

const port = Number(process.env.PORT || 3000);
const dataDir = path.resolve(process.env.DATA_DIR || 'data'); fs.mkdirSync(dataDir, { recursive: true });
const db = new DatabaseSync(path.join(dataDir, 'walkie.sqlite'));
db.exec(fs.readFileSync(path.join(__dirname, 'schema.sql'), 'utf8'));
const now = () => new Date().toISOString(); const id = () => crypto.randomUUID();
const hash = value => crypto.createHash('sha256').update(value).digest('hex');
function transaction(work) { db.exec('BEGIN IMMEDIATE'); try { const result=work(); db.exec('COMMIT'); return result; } catch (error) { db.exec('ROLLBACK'); throw error; } }
function seed() { const t=now(); if (!db.prepare('SELECT 1 FROM users LIMIT 1').get()) { db.prepare('INSERT INTO users VALUES (?,?,?,?,?,1,?)').run(id(),'operator','Demo Operator','operator',hash('ChangeMe123!'),t); db.prepare('INSERT INTO users VALUES (?,?,?,?,?,1,?)').run(id(),'admin','Demo Admin','admin',hash('ChangeMe123!'),t); for (const [h,n,d] of [['HR001','Anika Sharma','Operations'],['HR002','Rahul Verma','Logistics'],['HR003','Fatima Khan','Security']]) db.prepare('INSERT INTO employees VALUES (?,?,?,?,?,?,?)').run(id(),h,n,d,'active',t,t); for (const [a,s] of [['WT-001','SN-001'],['WT-002','SN-002'],['WT-003','SN-003']]) db.prepare('INSERT INTO devices VALUES (?,?,?,?,?,?,?,?,?,?)').run(id(),a,s,'Motorola','DP1400','AVAILABLE',null,'WTMS-'+crypto.randomBytes(8).toString('hex'),t,t); db.prepare('INSERT INTO chargers VALUES (?,?,1)').run(id(),'CH-01'); } } seed();
function json(res,status,value){ res.writeHead(status,{'Content-Type':'application/json','Access-Control-Allow-Origin':'*'}); res.end(JSON.stringify(value)); }
function body(req){ return new Promise((resolve,reject)=>{let raw='';req.on('data',x=>raw+=x);req.on('end',()=>{try{resolve(raw?JSON.parse(raw):{})}catch{reject(new Error('Invalid JSON'))}})}) }
function actor(req) { const username=req.headers['x-user']; const user=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(username); if(!user) throw Object.assign(new Error('Sign in is required'),{status:401}); return user; }
function requireRole(user,...roles){if(!roles.includes(user.role)) throw Object.assign(new Error('Permission denied'),{status:403});}
function activeShift(user){const s=db.prepare("SELECT * FROM shift_sessions WHERE user_id=? AND status='active'").get(user.id); if(!s) throw Object.assign(new Error('Start a shift before performing this operation'),{status:409}); return s;}
function event(tx, actor, type, entity, before, after, correlation) { const previous=db.prepare('SELECT entry_hash FROM audit_log ORDER BY occurred_at DESC LIMIT 1').get()?.entry_hash||''; const at=now(); const auditId=id(); const entryHash=hash([previous,type,entity.id,JSON.stringify(after),at].join('|')); db.prepare('INSERT INTO audit_log VALUES (?,?,?,?,?,?,?,?,?,?)').run(auditId,at,actor?.id||null,type,entity.type,entity.id,correlation,JSON.stringify(before||null),JSON.stringify(after||null),previous,entryHash); const seq=(db.prepare('SELECT COALESCE(MAX(sequence_no),0)+1 AS n FROM sync_outbox').get().n); const eventId=id(), payload=JSON.stringify({event_id:eventId,event_type:type,aggregate_id:entity.id,occurred_at_utc:at,actor_user_id:actor?.id||null,data:after}); db.prepare('INSERT INTO sync_outbox VALUES (?,?,?,?,?,?,?,?)').run(eventId,seq,type,entity.id,payload,hash(payload),'PENDING',at); return eventId; }
function issue(user,b){ requireRole(user,'operator'); const session=activeShift(user), correlation=id(); return transaction(()=>{const device=db.prepare('SELECT * FROM devices WHERE qr_token=?').get(b.qr_token); const employee=db.prepare("SELECT * FROM employees WHERE hrms_id=? AND status='active'").get(b.hrms_id); if(!device) throw new Error('QR credential is unknown'); if(!employee) throw new Error('Active employee not found'); if(device.operational_status!=='AVAILABLE') throw new Error('Device is not available'); if(db.prepare('SELECT 1 FROM issues WHERE device_id=? AND returned_at IS NULL').get(device.id)) throw new Error('Device already has an active issue'); if(db.prepare('SELECT 1 FROM issues WHERE employee_id=? AND returned_at IS NULL').get(employee.id)) throw new Error('Employee already has an active issue'); const issueId=id(), eventId=id(), at=now(); db.prepare('INSERT INTO issues VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)').run(issueId,device.id,employee.id,at,user.id,session.id,null,null,null,null,eventId); db.prepare('UPDATE devices SET operational_status=?,active_issue_id=?,updated_at=? WHERE id=?').run('ISSUED',issueId,at,device.id); db.prepare('INSERT INTO status_history VALUES (?,?,?,?,?,?,?,?)').run(id(),device.id,'AVAILABLE','ISSUED','issue',user.id,at,correlation); const outEvent=event(null,user,'ISSUE_CREATED',{type:'issue',id:issueId},device,{issue_id:issueId,device_id:device.id,employee_id:employee.id},correlation); return {issue_id:issueId,event_id:outEvent,asset_code:device.asset_code,employee:employee.display_name}; }); }
function returnDevice(user,b){ requireRole(user,'operator'); activeShift(user); const correlation=id(); return transaction(()=>{let issue; if(b.method==='hrms_fallback'){ if(!b.fallback_reason) throw new Error('Fallback reason is required'); const e=db.prepare('SELECT id FROM employees WHERE hrms_id=?').get(b.hrms_id); issue=e&&db.prepare('SELECT * FROM issues WHERE employee_id=? AND returned_at IS NULL').get(e.id); if(!issue||issue.device_id!==b.device_id) throw new Error('No matching active issue found'); } else {const d=db.prepare('SELECT id FROM devices WHERE qr_token=?').get(b.qr_token); issue=d&&db.prepare('SELECT * FROM issues WHERE device_id=? AND returned_at IS NULL').get(d.id); if(!issue) throw new Error('No active issue found');} const device=db.prepare('SELECT * FROM devices WHERE id=?').get(issue.device_id), at=now(); db.prepare('UPDATE issues SET returned_at=?,returned_by=?,return_method=?,fallback_reason=? WHERE id=?').run(at,user.id,b.method,b.fallback_reason||null,issue.id); db.prepare('UPDATE devices SET operational_status=?,active_issue_id=NULL,updated_at=? WHERE id=?').run('AVAILABLE',at,device.id); db.prepare('INSERT INTO status_history VALUES (?,?,?,?,?,?,?,?)').run(id(),device.id,'ISSUED','AVAILABLE','return',user.id,at,correlation); const eventId=event(null,user,'ISSUE_RETURNED',{type:'issue',id:issue.id},device,{issue_id:issue.id,method:b.method},correlation); return {issue_id:issue.id,event_id:eventId,asset_code:device.asset_code}; }); }
function charging(user,b){requireRole(user,'operator','admin');activeShift(user); return transaction(()=>{const charger=db.prepare('SELECT * FROM chargers WHERE charger_number=?').get(b.charger_number); if(!charger) throw new Error('Charger not found. Add it in the database first.'); const device=db.prepare('SELECT * FROM devices WHERE id=?').get(b.device_id); if(!device||device.operational_status!=='AVAILABLE') throw new Error('Only available devices can start charging'); const at=now(),correlation=id(); db.prepare('INSERT INTO charging_assignments VALUES (?,?,?,?,?,?)').run(id(),charger.id,device.id,at,null,user.id); db.prepare('UPDATE devices SET operational_status=?,updated_at=? WHERE id=?').run('CHARGING',at,device.id); db.prepare('INSERT INTO status_history VALUES (?,?,?,?,?,?,?,?)').run(id(),device.id,'AVAILABLE','CHARGING','charging_start',user.id,at,correlation); return {event_id:event(null,user,'CHARGING_STARTED',{type:'device',id:device.id},device,{charger_number:b.charger_number},correlation)}; })();}
function dashboard(){return {states:db.prepare('SELECT operational_status status,COUNT(*) count FROM devices GROUP BY operational_status').all(),issues:db.prepare('SELECT i.id,d.asset_code,e.display_name,i.issued_at FROM issues i JOIN devices d ON d.id=i.device_id JOIN employees e ON e.id=i.employee_id WHERE i.returned_at IS NULL').all(),outbox:db.prepare("SELECT status,COUNT(*) count FROM sync_outbox GROUP BY status").all(),recent:db.prepare('SELECT action,occurred_at,entity_type,entity_id FROM audit_log ORDER BY occurred_at DESC LIMIT 10').all()};}
const publicDir=path.join(__dirname,'..','public');
http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost'); const file=url.pathname==='/'?'index.html':url.pathname.slice(1);const p=path.join(publicDir,file); if(req.method==='GET'&&p.startsWith(publicDir)&&fs.existsSync(p)) {res.writeHead(200,{'Content-Type':p.endsWith('.js')?'application/javascript':'text/html'});return fs.createReadStream(p).pipe(res)} if(req.method==='GET'&&url.pathname==='/api/dashboard') return json(res,200,dashboard()); if(req.method==='GET'&&url.pathname==='/api/devices') return json(res,200,db.prepare('SELECT id,asset_code,serial_number,model,operational_status,qr_token FROM devices ORDER BY asset_code').all()); if(req.method==='GET'&&url.pathname==='/api/employees') return json(res,200,db.prepare("SELECT id,hrms_id,display_name,department FROM employees WHERE status='active' ORDER BY display_name").all()); if(req.method==='POST'&&url.pathname==='/api/login'){const b=await body(req),u=db.prepare('SELECT * FROM users WHERE username=? AND active=1').get(b.username); if(!u||u.password_hash!==hash(b.password)) return json(res,401,{error:'Invalid credentials'}); return json(res,200,{username:u.username,display_name:u.display_name,role:u.role});} const user=actor(req); if(req.method==='POST'&&url.pathname==='/api/shifts/start'){const s=transaction(()=>{const existing=db.prepare("SELECT * FROM shift_sessions WHERE user_id=? AND status='active'").get(user.id); if(existing)return existing; const row={id:id(),user_id:user.id,started_at:now(),ended_at:null,status:'active'};db.prepare('INSERT INTO shift_sessions VALUES (?,?,?,?,?)').run(row.id,row.user_id,row.started_at,null,row.status);return row;});return json(res,200,s)} if(req.method==='POST'&&url.pathname==='/api/shifts/end'){db.prepare("UPDATE shift_sessions SET status='closed',ended_at=? WHERE user_id=? AND status='active'").run(now(),user.id);return json(res,200,{ok:true})} const b=await body(req); if(req.method==='POST'&&url.pathname==='/api/issues')return json(res,201,issue(user,b)); if(req.method==='POST'&&url.pathname==='/api/returns')return json(res,200,returnDevice(user,b)); if(req.method==='POST'&&url.pathname==='/api/charging/start')return json(res,201,charging(user,b)); json(res,404,{error:'Not found'});}catch(e){json(res,e.status||400,{error:e.message});}}).listen(port,()=>console.log(`Walkie Talkie Management System running at http://localhost:${port}`));
